In [7]:
import numpy as np

A = np.arange(25).reshape(5,5)
np.save('demo1',A)

b=np.load('demo1.npy')
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Code 2

In [3]:
import numpy as np

D = np.asarray[[1,2,3,4,5,6,7,8,9,10],['a','b','c','d','e','f','g','h','i','j'],['D','D','D','C','D','D','E','D','D','D'],[23,45,12,67,87,56,45,88,98,76],[78,98,78,67,56,78,98,89,78,67],[78,89,97,67,78,89,87,65,78,98]]
np.savetxt('demo.csv',D,delimiter=",")


TypeError: 'builtin_function_or_method' object is not subscriptable