In [16]:
import numpy
a = numpy.array(object,dtype=None,copy=True,subok=False,ndmin = 0)
print(a)

<class 'object'>


In [17]:
a.max()

object

In [18]:
numpy.arange(0,12).reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [19]:
import numpy as np
def foo(x):
    return x*2  
A = np.arange(0,9).reshape((3,3))
np.apply_along_axis(foo,axis=1,arr=A)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [20]:
import numpy as np 
X,Y=np.arange(3),np.arange(3)
xy = np.array([[(x,y) for x in X]for y in Y])
print(xy)

[[[0 0]
  [1 0]
  [2 0]]

 [[0 1]
  [1 1]
  [2 1]]

 [[0 2]
  [1 2]
  [2 2]]]


In [21]:
import pandas as pd
s = pd.read_csv('iris.csv')
print(s)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa


In [24]:
s.to_hdf('iris.h5', key='s',mode='w')
pd.read_hdf('iris.h5','s')

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [26]:
f = pd.read_csv('pivvot.csv')
f

color  item     value
0  2 white  ball  0.091438
1  0 white   pen  0.495049
2  2 white   mug  0.956225
3    4 red  ball  0.394441
4    3 red   pen  0.501164
5    5 red   mug  0.561832
6  6 black  ball  0.879022
7  7 black   pen  0.610975
8  8 black   mug  0.093324

In [32]:
f.pivot_table(index=['item'],columns='color',values='value')

color   0 white   2 white     3 red     4 red     5 red   6 black   7 black  \
item                                                                          
ball        NaN  0.091438       NaN  0.394441       NaN  0.879022       NaN   
mug         NaN  0.956225       NaN       NaN  0.561832       NaN       NaN   
pen    0.495049       NaN  0.501164       NaN       NaN       NaN  0.610975   

color   8 black  
item             
ball        NaN  
mug    0.093324  
pen         NaN

In [34]:
t = pd.read_csv('final.csv')
t

color   object  price1  price2
0  white   Pencil    4.20    4.75
1    red      Pen    5.56    4.12
2  green      Pen    2.75    1.60
3    red  ashtray    0.56    0.75
4  green   Pencil    1.30    3.15

In [38]:
j=f.groupby(['color']).mean()
print(j)

            value
color            
0 white  0.495049
2 white  0.523832
3 red    0.501164
4 red    0.394441
5 red    0.561832
6 black  0.879022
7 black  0.610975
8 black  0.093324
