In [29]:
import numpy as np

a=np.arange(20).reshape(2,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


Code 2

In [23]:
b=np.arange(12).reshape(2,2,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


Code 3

In [24]:
c = np.arange(1,10).reshape(3,3)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Code 4

In [25]:
d = [1,2,3,4,5,6,7,8,9]
e = np.flipud(d)
print (e)

[9 8 7 6 5 4 3 2 1]


Code 5

In [26]:
f = np.ones((3,3))
f[1:-1,1:-1]=0
print(f)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


Code 6

In [32]:
A = np.arange(16).reshape(4,4)
print(A)
print(A[0:1])
print(A[0:2])
print(A[2:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


Code 7

In [31]:
import numpy as np
E = A[0:2]*A[2:]
print(E)

[[  0   9  20  33]
 [ 48  65  84 105]]


Code 8

In [ ]:
v = np.arange(12).reshape(3,4)
z,x,c,n=np.hsplit(v,4)
q = np.sum(z)
w = np.sum(x)
t = np.sum(c)
r = np.sum(n)
if q>w and q>t and q>r:
    print(q)
elif w>q and w>t and w>r:
    print(w)
elif r>w and r>t and r>q:
    print(r)
elif t>w and t>q and t>r:
    print(t)

21
