In [1]:
import numpy as np

a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element from 1st dim:',a[-1,-1])

Last element from 1st dim: 10


In [3]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[:2,1:3]
print(b)
print(a[0,1])
b[0,0] = 77
print(a[0,1])

[[2 3]
 [6 7]]
2
77


In [5]:
import numpy as np

a = np.arange(20)
print("\n a[-8:17:2] = ",a[-8:17:2])
print("\n a[10:]",a[10:])


 a[-8:17:2] =  [12 14 16]

 a[10:] [10 11 12 13 14 15 16 17 18 19]


In [6]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2),axis=0)#row wise
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7]:
A=np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
[B,C] = np.hsplit(A,2)
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [9]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [10]:
[B,C]=np.vsplit(A,2)
B
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
[A1,A2,A3]=np.split(A,[1,3],axis=0)
A1

array([[0, 1, 2, 3]])

In [12]:
[A1,A2,A3]=np.split(A,[1,3],axis=1)
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [13]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [14]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [15]:
a = np.reshape(np.arange(16),(4,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [16]:
large_values = (a>10)
print(large_values)

[[False False False False]
 [False False False False]
 [False False False  True]
 [ True  True  True  True]]


In [17]:
even_values = (a%2 == 0)
print(even_values)

[[ True False  True False]
 [ True False  True False]
 [ True False  True False]
 [ True False  True False]]


In [18]:
print(a[even_values])

[ 0  2  4  6  8 10 12 14]
